stages:
  - build
  - deploy

variables:
  DOCKERHUB_USER: tr0f1mka
  DOCKERHUB_REPOSITORY_NAME: cson-frontend

.docker_template:
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - docker -v
    - docker info
    - docker login docker.io -u "$FRONTEND_USERNAME" -p "$FRONTEND_PASSWORD"

build-job:
  image: docker:27
  stage: build
  extends: .docker_template
  script:
    - docker build -t $DOCKERHUB_USER/$DOCKERHUB_REPOSITORY_NAME:latest .
    - docker push $DOCKERHUB_USER/$DOCKERHUB_REPOSITORY_NAME:latest
  only:
    - main

.deploy_template:
  image: kroniak/ssh-client:latest
  before_script:
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_ed25519
    - >-
      echo -e "Host *\n  StrictHostKeyChecking no\n  UserKnownHostsFile
      /dev/null" > ~/.ssh/config
    - chmod 600 ~/.ssh/id_ed25519

deploy-job:
  image: docker:27
  stage: deploy
  extends: .deploy_template
  script:
    - ssh -i ~/.ssh/id_ed25519 root@$SSH_REMOTE_HOST "
      cd /root/projects/converter &&
      docker stop frontend || true &&
      docker rm frontend || true &&
      docker image rm $DOCKERHUB_USER/$DOCKERHUB_REPOSITORY_NAME:latest || true &&
      docker pull $DOCKERHUB_USER/$DOCKERHUB_REPOSITORY_NAME:latest &&
      docker run -d --name=frontend -p 127.0.0.1:4200:4200 $DOCKERHUB_USER/$DOCKERHUB_REPOSITORY_NAME:latest
      "
  only:
    - main
  when: manual

